name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions on ${{ github.ref_name }} [${{ github.event_name }}]

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger info
        run: |
          echo "Trigger: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Confirm checkout
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
